//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/Input/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""KeyInput"",
            ""id"": ""f998ef23-799d-4e2d-8f4b-ffd1c5e8c93e"",
            ""actions"": [
                {
                    ""name"": ""Key_A"",
                    ""type"": ""Value"",
                    ""id"": ""7827c1f5-522f-4c0e-a087-94869dd262cd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_B"",
                    ""type"": ""Value"",
                    ""id"": ""a25ab4ef-4438-4114-b391-b93d8d59eb5c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_C"",
                    ""type"": ""Value"",
                    ""id"": ""e04f72df-122d-4ce7-a208-ef3249c96ff6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_D"",
                    ""type"": ""Value"",
                    ""id"": ""6900c764-c443-4c5e-a57d-918e431b974f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_E"",
                    ""type"": ""Value"",
                    ""id"": ""d52d455e-0efa-44d5-aa9c-e01413c465a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_F"",
                    ""type"": ""Value"",
                    ""id"": ""11598f1c-47fe-4d73-bd95-83e77f0bbfdd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_G"",
                    ""type"": ""Value"",
                    ""id"": ""1470ed23-344e-4172-b14b-8a7fb5c43cbb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_H"",
                    ""type"": ""Value"",
                    ""id"": ""5b241bc6-ba23-456f-ac23-fc738ff212c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_I"",
                    ""type"": ""Value"",
                    ""id"": ""53c1d45e-a22c-4c58-8f62-fb31e2cd3d7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_J"",
                    ""type"": ""Value"",
                    ""id"": ""fb579d96-d4e9-41fc-a189-3ce2bb739e13"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_K"",
                    ""type"": ""Value"",
                    ""id"": ""63bb9098-402b-421f-936f-8fb718f6d008"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_L"",
                    ""type"": ""Value"",
                    ""id"": ""56be23f3-2fbf-4308-bcc3-3d859a864561"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_M"",
                    ""type"": ""Value"",
                    ""id"": ""89446336-45ee-4747-ae21-c78e38468a1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_N"",
                    ""type"": ""Value"",
                    ""id"": ""2053fd9b-36dc-4f7c-acd6-48d86436816c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_O"",
                    ""type"": ""Value"",
                    ""id"": ""e490dc08-4f23-4524-9445-ed9ed24f6a0a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_P"",
                    ""type"": ""Value"",
                    ""id"": ""aaf54857-3997-4d7b-a37e-4d8c0a529252"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_Q"",
                    ""type"": ""Value"",
                    ""id"": ""36a9e851-9484-41a8-bd4c-44c52d0c4cf3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_R"",
                    ""type"": ""Value"",
                    ""id"": ""4b7d66d0-c18d-4675-83cf-ddf26e8398e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_S"",
                    ""type"": ""Value"",
                    ""id"": ""a64c38f7-b5d2-4462-ac2c-e867f4ba48c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_T"",
                    ""type"": ""Value"",
                    ""id"": ""95efb7b7-2406-430c-8281-5998196b885e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_U"",
                    ""type"": ""Value"",
                    ""id"": ""c43c665f-9947-4c87-bb72-2b1e1838ce9f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_V"",
                    ""type"": ""Value"",
                    ""id"": ""fd5e55ab-7e1c-42f1-b30d-cb385cf927a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_W"",
                    ""type"": ""Value"",
                    ""id"": ""39a8e647-cb65-48fb-b4f5-4a5e288131ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_X"",
                    ""type"": ""Value"",
                    ""id"": ""79c55075-67ae-45c0-b526-c8e5b3f9f4e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_Y"",
                    ""type"": ""Value"",
                    ""id"": ""14bd27a2-1e6c-4496-a820-7670749b1c4e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Key_Z"",
                    ""type"": ""Value"",
                    ""id"": ""15942112-802b-4071-a568-5106582f1fe6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Any"",
                    ""type"": ""Value"",
                    ""id"": ""ae39d63f-a284-46a5-bcdd-aa66d8c72060"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Value"",
                    ""id"": ""2e19e6e2-bb5d-4d43-84c5-13b1549a19e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Value"",
                    ""id"": ""e5523cef-59f2-4c34-99cb-677a08eec7e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d4e16ddd-676c-42ee-9b04-53744b4e1e82"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a73b017-8190-4b02-ae31-54222850d1dc"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbb1bd2-9db8-4f63-ae68-32cb05db08de"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1498b88-6d50-4cfd-9e73-5bfb934341d7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43cce5fa-6c20-471f-b9d0-71f016f8b2da"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9f8225d-533f-4afd-9932-c1bdc19afa47"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b98222b-bf04-43d4-a5ab-992bf69bc728"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d059ba0-00ce-4414-8575-ccbc168372a9"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_H"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66be85d7-61d3-4e12-996f-ad4806d0f2e2"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5f1717a-0147-4660-85f3-3576ad074d1b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_I"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7be9200-42c3-4d9e-ad31-fb20686be91b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad02bcfa-aa52-4afc-bd39-035227bf706c"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa862264-855a-46a5-84f3-ccd521be7791"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_M"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15221b6a-2d90-4943-8019-da1c7f16bd91"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_N"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6638f3e-edd5-4183-9981-e5f484eebed7"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_O"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f51978b7-7460-4c64-92b6-1a0d4e015071"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_P"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dae6301d-3e2b-4d6e-9ddf-b3b60a124266"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bc4c89d-b50c-4821-8eb1-3aec91abe668"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aabafbba-9d6a-438b-96dc-a0157ff31950"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df422356-aab8-4b31-bf1b-add9bc66c4a5"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_T"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6970bb1-7ba3-4aa8-bd8e-224afff05320"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_U"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7fef131-1883-49cc-9301-b6c4aa73310f"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_V"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b59f5168-f1bf-4139-b2ea-3ad700023f57"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_W"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af7fc110-087c-4fcd-8abd-5f4ae0482877"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77557f0c-aa30-4201-9587-6a6f1d2ca839"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8edd2fea-7576-4635-88a7-3ef4f8ca4b83"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key_Z"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12c082e8-6037-4c7d-b896-aa0989ad1f1a"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""519136cf-8dab-43b1-b0a3-8bf90b13763e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38d77355-ef3a-484b-9a3b-04b8515ed463"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerTouch"",
            ""id"": ""28f3e64a-ad4b-4452-9575-978f30980ea0"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""1d335f32-09f8-4e52-99ee-55efcd3c1ca4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7f2685b-50e9-4aed-a053-7e353cbf9843"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa9f745d-0e5f-4d3e-a77c-2928b6998ca6"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyInput
        m_KeyInput = asset.FindActionMap("KeyInput", throwIfNotFound: true);
        m_KeyInput_Key_A = m_KeyInput.FindAction("Key_A", throwIfNotFound: true);
        m_KeyInput_Key_B = m_KeyInput.FindAction("Key_B", throwIfNotFound: true);
        m_KeyInput_Key_C = m_KeyInput.FindAction("Key_C", throwIfNotFound: true);
        m_KeyInput_Key_D = m_KeyInput.FindAction("Key_D", throwIfNotFound: true);
        m_KeyInput_Key_E = m_KeyInput.FindAction("Key_E", throwIfNotFound: true);
        m_KeyInput_Key_F = m_KeyInput.FindAction("Key_F", throwIfNotFound: true);
        m_KeyInput_Key_G = m_KeyInput.FindAction("Key_G", throwIfNotFound: true);
        m_KeyInput_Key_H = m_KeyInput.FindAction("Key_H", throwIfNotFound: true);
        m_KeyInput_Key_I = m_KeyInput.FindAction("Key_I", throwIfNotFound: true);
        m_KeyInput_Key_J = m_KeyInput.FindAction("Key_J", throwIfNotFound: true);
        m_KeyInput_Key_K = m_KeyInput.FindAction("Key_K", throwIfNotFound: true);
        m_KeyInput_Key_L = m_KeyInput.FindAction("Key_L", throwIfNotFound: true);
        m_KeyInput_Key_M = m_KeyInput.FindAction("Key_M", throwIfNotFound: true);
        m_KeyInput_Key_N = m_KeyInput.FindAction("Key_N", throwIfNotFound: true);
        m_KeyInput_Key_O = m_KeyInput.FindAction("Key_O", throwIfNotFound: true);
        m_KeyInput_Key_P = m_KeyInput.FindAction("Key_P", throwIfNotFound: true);
        m_KeyInput_Key_Q = m_KeyInput.FindAction("Key_Q", throwIfNotFound: true);
        m_KeyInput_Key_R = m_KeyInput.FindAction("Key_R", throwIfNotFound: true);
        m_KeyInput_Key_S = m_KeyInput.FindAction("Key_S", throwIfNotFound: true);
        m_KeyInput_Key_T = m_KeyInput.FindAction("Key_T", throwIfNotFound: true);
        m_KeyInput_Key_U = m_KeyInput.FindAction("Key_U", throwIfNotFound: true);
        m_KeyInput_Key_V = m_KeyInput.FindAction("Key_V", throwIfNotFound: true);
        m_KeyInput_Key_W = m_KeyInput.FindAction("Key_W", throwIfNotFound: true);
        m_KeyInput_Key_X = m_KeyInput.FindAction("Key_X", throwIfNotFound: true);
        m_KeyInput_Key_Y = m_KeyInput.FindAction("Key_Y", throwIfNotFound: true);
        m_KeyInput_Key_Z = m_KeyInput.FindAction("Key_Z", throwIfNotFound: true);
        m_KeyInput_Any = m_KeyInput.FindAction("Any", throwIfNotFound: true);
        m_KeyInput_Space = m_KeyInput.FindAction("Space", throwIfNotFound: true);
        m_KeyInput_Enter = m_KeyInput.FindAction("Enter", throwIfNotFound: true);
        // PlayerTouch
        m_PlayerTouch = asset.FindActionMap("PlayerTouch", throwIfNotFound: true);
        m_PlayerTouch_Tap = m_PlayerTouch.FindAction("Tap", throwIfNotFound: true);
    }

    ~@PlayerAction()
    {
        UnityEngine.Debug.Assert(!m_KeyInput.enabled, "This will cause a leak and performance issues, PlayerAction.KeyInput.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerTouch.enabled, "This will cause a leak and performance issues, PlayerAction.PlayerTouch.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyInput
    private readonly InputActionMap m_KeyInput;
    private List<IKeyInputActions> m_KeyInputActionsCallbackInterfaces = new List<IKeyInputActions>();
    private readonly InputAction m_KeyInput_Key_A;
    private readonly InputAction m_KeyInput_Key_B;
    private readonly InputAction m_KeyInput_Key_C;
    private readonly InputAction m_KeyInput_Key_D;
    private readonly InputAction m_KeyInput_Key_E;
    private readonly InputAction m_KeyInput_Key_F;
    private readonly InputAction m_KeyInput_Key_G;
    private readonly InputAction m_KeyInput_Key_H;
    private readonly InputAction m_KeyInput_Key_I;
    private readonly InputAction m_KeyInput_Key_J;
    private readonly InputAction m_KeyInput_Key_K;
    private readonly InputAction m_KeyInput_Key_L;
    private readonly InputAction m_KeyInput_Key_M;
    private readonly InputAction m_KeyInput_Key_N;
    private readonly InputAction m_KeyInput_Key_O;
    private readonly InputAction m_KeyInput_Key_P;
    private readonly InputAction m_KeyInput_Key_Q;
    private readonly InputAction m_KeyInput_Key_R;
    private readonly InputAction m_KeyInput_Key_S;
    private readonly InputAction m_KeyInput_Key_T;
    private readonly InputAction m_KeyInput_Key_U;
    private readonly InputAction m_KeyInput_Key_V;
    private readonly InputAction m_KeyInput_Key_W;
    private readonly InputAction m_KeyInput_Key_X;
    private readonly InputAction m_KeyInput_Key_Y;
    private readonly InputAction m_KeyInput_Key_Z;
    private readonly InputAction m_KeyInput_Any;
    private readonly InputAction m_KeyInput_Space;
    private readonly InputAction m_KeyInput_Enter;
    public struct KeyInputActions
    {
        private @PlayerAction m_Wrapper;
        public KeyInputActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Key_A => m_Wrapper.m_KeyInput_Key_A;
        public InputAction @Key_B => m_Wrapper.m_KeyInput_Key_B;
        public InputAction @Key_C => m_Wrapper.m_KeyInput_Key_C;
        public InputAction @Key_D => m_Wrapper.m_KeyInput_Key_D;
        public InputAction @Key_E => m_Wrapper.m_KeyInput_Key_E;
        public InputAction @Key_F => m_Wrapper.m_KeyInput_Key_F;
        public InputAction @Key_G => m_Wrapper.m_KeyInput_Key_G;
        public InputAction @Key_H => m_Wrapper.m_KeyInput_Key_H;
        public InputAction @Key_I => m_Wrapper.m_KeyInput_Key_I;
        public InputAction @Key_J => m_Wrapper.m_KeyInput_Key_J;
        public InputAction @Key_K => m_Wrapper.m_KeyInput_Key_K;
        public InputAction @Key_L => m_Wrapper.m_KeyInput_Key_L;
        public InputAction @Key_M => m_Wrapper.m_KeyInput_Key_M;
        public InputAction @Key_N => m_Wrapper.m_KeyInput_Key_N;
        public InputAction @Key_O => m_Wrapper.m_KeyInput_Key_O;
        public InputAction @Key_P => m_Wrapper.m_KeyInput_Key_P;
        public InputAction @Key_Q => m_Wrapper.m_KeyInput_Key_Q;
        public InputAction @Key_R => m_Wrapper.m_KeyInput_Key_R;
        public InputAction @Key_S => m_Wrapper.m_KeyInput_Key_S;
        public InputAction @Key_T => m_Wrapper.m_KeyInput_Key_T;
        public InputAction @Key_U => m_Wrapper.m_KeyInput_Key_U;
        public InputAction @Key_V => m_Wrapper.m_KeyInput_Key_V;
        public InputAction @Key_W => m_Wrapper.m_KeyInput_Key_W;
        public InputAction @Key_X => m_Wrapper.m_KeyInput_Key_X;
        public InputAction @Key_Y => m_Wrapper.m_KeyInput_Key_Y;
        public InputAction @Key_Z => m_Wrapper.m_KeyInput_Key_Z;
        public InputAction @Any => m_Wrapper.m_KeyInput_Any;
        public InputAction @Space => m_Wrapper.m_KeyInput_Space;
        public InputAction @Enter => m_Wrapper.m_KeyInput_Enter;
        public InputActionMap Get() { return m_Wrapper.m_KeyInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyInputActions set) { return set.Get(); }
        public void AddCallbacks(IKeyInputActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyInputActionsCallbackInterfaces.Add(instance);
            @Key_A.started += instance.OnKey_A;
            @Key_A.performed += instance.OnKey_A;
            @Key_A.canceled += instance.OnKey_A;
            @Key_B.started += instance.OnKey_B;
            @Key_B.performed += instance.OnKey_B;
            @Key_B.canceled += instance.OnKey_B;
            @Key_C.started += instance.OnKey_C;
            @Key_C.performed += instance.OnKey_C;
            @Key_C.canceled += instance.OnKey_C;
            @Key_D.started += instance.OnKey_D;
            @Key_D.performed += instance.OnKey_D;
            @Key_D.canceled += instance.OnKey_D;
            @Key_E.started += instance.OnKey_E;
            @Key_E.performed += instance.OnKey_E;
            @Key_E.canceled += instance.OnKey_E;
            @Key_F.started += instance.OnKey_F;
            @Key_F.performed += instance.OnKey_F;
            @Key_F.canceled += instance.OnKey_F;
            @Key_G.started += instance.OnKey_G;
            @Key_G.performed += instance.OnKey_G;
            @Key_G.canceled += instance.OnKey_G;
            @Key_H.started += instance.OnKey_H;
            @Key_H.performed += instance.OnKey_H;
            @Key_H.canceled += instance.OnKey_H;
            @Key_I.started += instance.OnKey_I;
            @Key_I.performed += instance.OnKey_I;
            @Key_I.canceled += instance.OnKey_I;
            @Key_J.started += instance.OnKey_J;
            @Key_J.performed += instance.OnKey_J;
            @Key_J.canceled += instance.OnKey_J;
            @Key_K.started += instance.OnKey_K;
            @Key_K.performed += instance.OnKey_K;
            @Key_K.canceled += instance.OnKey_K;
            @Key_L.started += instance.OnKey_L;
            @Key_L.performed += instance.OnKey_L;
            @Key_L.canceled += instance.OnKey_L;
            @Key_M.started += instance.OnKey_M;
            @Key_M.performed += instance.OnKey_M;
            @Key_M.canceled += instance.OnKey_M;
            @Key_N.started += instance.OnKey_N;
            @Key_N.performed += instance.OnKey_N;
            @Key_N.canceled += instance.OnKey_N;
            @Key_O.started += instance.OnKey_O;
            @Key_O.performed += instance.OnKey_O;
            @Key_O.canceled += instance.OnKey_O;
            @Key_P.started += instance.OnKey_P;
            @Key_P.performed += instance.OnKey_P;
            @Key_P.canceled += instance.OnKey_P;
            @Key_Q.started += instance.OnKey_Q;
            @Key_Q.performed += instance.OnKey_Q;
            @Key_Q.canceled += instance.OnKey_Q;
            @Key_R.started += instance.OnKey_R;
            @Key_R.performed += instance.OnKey_R;
            @Key_R.canceled += instance.OnKey_R;
            @Key_S.started += instance.OnKey_S;
            @Key_S.performed += instance.OnKey_S;
            @Key_S.canceled += instance.OnKey_S;
            @Key_T.started += instance.OnKey_T;
            @Key_T.performed += instance.OnKey_T;
            @Key_T.canceled += instance.OnKey_T;
            @Key_U.started += instance.OnKey_U;
            @Key_U.performed += instance.OnKey_U;
            @Key_U.canceled += instance.OnKey_U;
            @Key_V.started += instance.OnKey_V;
            @Key_V.performed += instance.OnKey_V;
            @Key_V.canceled += instance.OnKey_V;
            @Key_W.started += instance.OnKey_W;
            @Key_W.performed += instance.OnKey_W;
            @Key_W.canceled += instance.OnKey_W;
            @Key_X.started += instance.OnKey_X;
            @Key_X.performed += instance.OnKey_X;
            @Key_X.canceled += instance.OnKey_X;
            @Key_Y.started += instance.OnKey_Y;
            @Key_Y.performed += instance.OnKey_Y;
            @Key_Y.canceled += instance.OnKey_Y;
            @Key_Z.started += instance.OnKey_Z;
            @Key_Z.performed += instance.OnKey_Z;
            @Key_Z.canceled += instance.OnKey_Z;
            @Any.started += instance.OnAny;
            @Any.performed += instance.OnAny;
            @Any.canceled += instance.OnAny;
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
        }

        private void UnregisterCallbacks(IKeyInputActions instance)
        {
            @Key_A.started -= instance.OnKey_A;
            @Key_A.performed -= instance.OnKey_A;
            @Key_A.canceled -= instance.OnKey_A;
            @Key_B.started -= instance.OnKey_B;
            @Key_B.performed -= instance.OnKey_B;
            @Key_B.canceled -= instance.OnKey_B;
            @Key_C.started -= instance.OnKey_C;
            @Key_C.performed -= instance.OnKey_C;
            @Key_C.canceled -= instance.OnKey_C;
            @Key_D.started -= instance.OnKey_D;
            @Key_D.performed -= instance.OnKey_D;
            @Key_D.canceled -= instance.OnKey_D;
            @Key_E.started -= instance.OnKey_E;
            @Key_E.performed -= instance.OnKey_E;
            @Key_E.canceled -= instance.OnKey_E;
            @Key_F.started -= instance.OnKey_F;
            @Key_F.performed -= instance.OnKey_F;
            @Key_F.canceled -= instance.OnKey_F;
            @Key_G.started -= instance.OnKey_G;
            @Key_G.performed -= instance.OnKey_G;
            @Key_G.canceled -= instance.OnKey_G;
            @Key_H.started -= instance.OnKey_H;
            @Key_H.performed -= instance.OnKey_H;
            @Key_H.canceled -= instance.OnKey_H;
            @Key_I.started -= instance.OnKey_I;
            @Key_I.performed -= instance.OnKey_I;
            @Key_I.canceled -= instance.OnKey_I;
            @Key_J.started -= instance.OnKey_J;
            @Key_J.performed -= instance.OnKey_J;
            @Key_J.canceled -= instance.OnKey_J;
            @Key_K.started -= instance.OnKey_K;
            @Key_K.performed -= instance.OnKey_K;
            @Key_K.canceled -= instance.OnKey_K;
            @Key_L.started -= instance.OnKey_L;
            @Key_L.performed -= instance.OnKey_L;
            @Key_L.canceled -= instance.OnKey_L;
            @Key_M.started -= instance.OnKey_M;
            @Key_M.performed -= instance.OnKey_M;
            @Key_M.canceled -= instance.OnKey_M;
            @Key_N.started -= instance.OnKey_N;
            @Key_N.performed -= instance.OnKey_N;
            @Key_N.canceled -= instance.OnKey_N;
            @Key_O.started -= instance.OnKey_O;
            @Key_O.performed -= instance.OnKey_O;
            @Key_O.canceled -= instance.OnKey_O;
            @Key_P.started -= instance.OnKey_P;
            @Key_P.performed -= instance.OnKey_P;
            @Key_P.canceled -= instance.OnKey_P;
            @Key_Q.started -= instance.OnKey_Q;
            @Key_Q.performed -= instance.OnKey_Q;
            @Key_Q.canceled -= instance.OnKey_Q;
            @Key_R.started -= instance.OnKey_R;
            @Key_R.performed -= instance.OnKey_R;
            @Key_R.canceled -= instance.OnKey_R;
            @Key_S.started -= instance.OnKey_S;
            @Key_S.performed -= instance.OnKey_S;
            @Key_S.canceled -= instance.OnKey_S;
            @Key_T.started -= instance.OnKey_T;
            @Key_T.performed -= instance.OnKey_T;
            @Key_T.canceled -= instance.OnKey_T;
            @Key_U.started -= instance.OnKey_U;
            @Key_U.performed -= instance.OnKey_U;
            @Key_U.canceled -= instance.OnKey_U;
            @Key_V.started -= instance.OnKey_V;
            @Key_V.performed -= instance.OnKey_V;
            @Key_V.canceled -= instance.OnKey_V;
            @Key_W.started -= instance.OnKey_W;
            @Key_W.performed -= instance.OnKey_W;
            @Key_W.canceled -= instance.OnKey_W;
            @Key_X.started -= instance.OnKey_X;
            @Key_X.performed -= instance.OnKey_X;
            @Key_X.canceled -= instance.OnKey_X;
            @Key_Y.started -= instance.OnKey_Y;
            @Key_Y.performed -= instance.OnKey_Y;
            @Key_Y.canceled -= instance.OnKey_Y;
            @Key_Z.started -= instance.OnKey_Z;
            @Key_Z.performed -= instance.OnKey_Z;
            @Key_Z.canceled -= instance.OnKey_Z;
            @Any.started -= instance.OnAny;
            @Any.performed -= instance.OnAny;
            @Any.canceled -= instance.OnAny;
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
        }

        public void RemoveCallbacks(IKeyInputActions instance)
        {
            if (m_Wrapper.m_KeyInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyInputActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyInputActions @KeyInput => new KeyInputActions(this);

    // PlayerTouch
    private readonly InputActionMap m_PlayerTouch;
    private List<IPlayerTouchActions> m_PlayerTouchActionsCallbackInterfaces = new List<IPlayerTouchActions>();
    private readonly InputAction m_PlayerTouch_Tap;
    public struct PlayerTouchActions
    {
        private @PlayerAction m_Wrapper;
        public PlayerTouchActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_PlayerTouch_Tap;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTouch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTouchActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerTouchActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTouchActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
        }

        private void UnregisterCallbacks(IPlayerTouchActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
        }

        public void RemoveCallbacks(IPlayerTouchActions instance)
        {
            if (m_Wrapper.m_PlayerTouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerTouchActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerTouchActions @PlayerTouch => new PlayerTouchActions(this);
    public interface IKeyInputActions
    {
        void OnKey_A(InputAction.CallbackContext context);
        void OnKey_B(InputAction.CallbackContext context);
        void OnKey_C(InputAction.CallbackContext context);
        void OnKey_D(InputAction.CallbackContext context);
        void OnKey_E(InputAction.CallbackContext context);
        void OnKey_F(InputAction.CallbackContext context);
        void OnKey_G(InputAction.CallbackContext context);
        void OnKey_H(InputAction.CallbackContext context);
        void OnKey_I(InputAction.CallbackContext context);
        void OnKey_J(InputAction.CallbackContext context);
        void OnKey_K(InputAction.CallbackContext context);
        void OnKey_L(InputAction.CallbackContext context);
        void OnKey_M(InputAction.CallbackContext context);
        void OnKey_N(InputAction.CallbackContext context);
        void OnKey_O(InputAction.CallbackContext context);
        void OnKey_P(InputAction.CallbackContext context);
        void OnKey_Q(InputAction.CallbackContext context);
        void OnKey_R(InputAction.CallbackContext context);
        void OnKey_S(InputAction.CallbackContext context);
        void OnKey_T(InputAction.CallbackContext context);
        void OnKey_U(InputAction.CallbackContext context);
        void OnKey_V(InputAction.CallbackContext context);
        void OnKey_W(InputAction.CallbackContext context);
        void OnKey_X(InputAction.CallbackContext context);
        void OnKey_Y(InputAction.CallbackContext context);
        void OnKey_Z(InputAction.CallbackContext context);
        void OnAny(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
    }
    public interface IPlayerTouchActions
    {
        void OnTap(InputAction.CallbackContext context);
    }
}
